server:
  port: 7777

spring:
  application:
    name: on-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service-one?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 10000
      idle-timeout: 30000
      max-lifetime: 900000
      maximum-pool-size: 30
      minimum-idle: 10
      pool-name: HikariCP
      validation-timeout: 1000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*/*.xml
  type-aliases-package: com.yi.service.logic.entity

tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
