server:
    port: 3311
    servlet:
        context-path: /producer
spring:
    application:
        name: producer
    cloud:
        stream:
            binders: #需要绑定的rabbitmq的服务信息
                rabbit_cluster:
                    environment:
                        spring:
                            rabbitmq:
                                addresses: 127.0.0.1:5672
                                password: guest
                                username: guest
                                virtual-host: / #虚拟路径
                    type: rabbit
            bindings: #服务的整合处理
                #inputs 对应消费者，outputs 对应生产者
                #Stream中的消息通信方式遵循了发布-订阅模式
                #消费者宕机：如果未配置group，则消费者上线后无法消费之前的消息（消息丢失）；如果配置了group，则消费上线后可以消费之前的消息（消息持久化）
                output_channel:
                    binder: rabbit_cluster
                    destination: exchange-3 #exchange名称,交换模式默认是topic;把SpringCloud Stream的消息输出通道绑定到RabbitMQ的exchange-test交换器。
                    group: queue-3 #分组=Queue名称，如果不设置会使用默认的组流水号
