server:
  port: 3301

spring:
  application:
    name: config-single-server  # 应用名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tianyi1/springcloudconfig #配置文件所在仓库
          username: 2014628402@qq.com
          password: TIANZHONGHAI658
          default-label: master #配置文件分支
          search-paths: config  #配置文件所在根目录

#eureka 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true